url: http://127.0.0.1:4000/
name: James Stone
description: A Personal Blog by James Stone.
exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
production_url:  http://127.0.0.1:4000/
rss_path:        rss.xml
atom_path:       atom.xml
